FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y curl unzip && \
    rm -rf /var/lib/apt/lists/*

COPY build.gradle settings.gradle gradlew ./
COPY gradle gradle/
RUN chmod +x gradlew

RUN ./gradlew dependencies --no-daemon

COPY . .

EXPOSE 8005

CMD ["./gradlew", "bootRun", "--no-daemon"]