FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

RUN apk update && \
    apk add --no-cache curl unzip

COPY build.gradle settings.gradle ./
COPY gradle ./gradle
COPY gradlew ./
COPY . ./
RUN chmod a+x ./gradlew
RUN ./gradlew dependencies

EXPOSE 8005

CMD ["./gradlew", "bootRun", "--stacktrace", "--info"]
