FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y maven && \
    rm -rf /var/lib/apt/lists/*

COPY pom.xml ./
RUN mvn dependency:go-offline -B

COPY . .
RUN chmod +x mvnw

EXPOSE 8003

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]