FROM openjdk:17-jdk-slim

WORKDIR /app

RUN apt-get update && \
    apt-get install -y maven

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY . .

EXPOSE 8003

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]