FROM maven:3.9-eclipse-temurin-17-alpine

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline

COPY . ./
RUN chmod a+x ./mvnw

EXPOSE 8003

CMD ["./mvnw", "spring-boot:run", "-Dspring-boot.run.profiles=dev"]
